version: '3'

networks:
  laravel:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs:/etc/nginx/certs
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql  
    networks:
      - laravel
    working_dir: /var/www/html

  php:
    build:
      context: ./build
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel

  mysql:
    image: mysql:latest
    tty: true
    volumes:
      - ./data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_DATABASE=laravel
      - MYSQL_PASSWORD=secret
    networks:
      - laravel

  myadmin:
    image: phpmyadmin
    ports: 
      - "33060:80"
    environment: 
      - PMA_HOST=mysql
    depends_on: 
      - mysql
    networks: 
      - laravel

  redis:
    image: redis:6.2.3
    ports:
      - "6379:6379"
    volumes: 
      - $PWD/redis:/var/lib/redis
      - $PWD/config/redis/redis.conf:/usr/local/etc/redis/redis.conf