version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - $NG_PORT:80
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs:/etc/nginx/certs
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql  
    networks:
      - laravel
    working_dir: /var/www/html

  php:
    build:
      context: ./build
      args:
        PHP_VER: $PHP_VER
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel

  mysql:
    image: mysql:latest
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    ports: 
      - $MYSQL_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_DATABASE=laravel
      - MYSQL_PASSWORD=secret
    networks:
      - laravel

  myadmin:
    image: phpmyadmin
    ports: 
      - $PMD_PORT:80
    environment: 
      - PMA_HOST=mysql
    depends_on: 
      - mysql
    networks: 
      - laravel

  redis:
    image: redis:$REDIS_VER
    ports:
      - $REDIS_PORT:6379
    volumes: 
      - $PWD/data/redis:/var/lib/redis
      - $PWD/config/redis/redis.conf:/usr/local/etc/redis/redis.conf

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ES_IMG_VER
    environment:
      - discovery.type=single-node

    # @todo this is not working at this time.
    # volumes:
      # - $PWD/data/es/node:/usr/share/elasticsearch/data
      # - ./log/es:/usr/share/elasticsearch/logs
    ports:
      - $ES_PORT:9200
    networks:
      - laravel

networks:
  laravel:
    driver: bridge